fun main() {


    var c1: Figure = Circle()
    var c2 = Circle(10f, 1f, 1f)
    println("CIRCLE")
    println("Areas:")
    println(c1.area())
    println(c2.area())
    var c3 = Circle(c2)
    println(c3.area())
    println("")
    println("Resize:")
    c2.resize(10)
    println(c2.area())
    c3.resize(-10)
    println(c3.area())
    c2.resize(0)
    println(c2.area())
    println("")
    println("Rotation:")
    print(c3.x)
    print(' ')
    println(c3.y)
    c3.rotate(RotateDirection.Clockwise, 3, 3)
    print(c3.x)
    print(' ')
    println(c3.y)
    c3.rotate(RotateDirection.Clockwise, 3, 3)
    print(c3.x)
    print(' ')
    println(c3.y)
    c3.rotate(RotateDirection.Clockwise, 3, 3)
    print(c3.x)
    print(' ')
    println(c3.y)
    println("")
    println("SQUARE")
    var s1 = Square()
    var s2 = Square(10f, 3f, 4f)
    println("Areas:")
    println(s1.area())
    println(s2.area())
    println("")
    println("Resize:")
    s1.resize(10)
    println(s1.area())
    s2.resize(-10)
    println(s2.area())
    println("Rotation:")
    print(s2.x)
    print(' ')
    println(s2.y)
    s2.rotate(RotateDirection.Clockwise, 3, 3)
    print(s2.x)
    print(' ')
    println(s2.y)
    s2.rotate(RotateDirection.Clockwise, 3, 3)
    print(s2.x)
    print(' ')
    println(s2.y)
    s2.rotate(RotateDirection.Clockwise, 3, 3)
    print(s2.x)
    print(' ')
    println(s2.y)
    println("")
    s2.rotate(RotateDirection.Clockwise, 3, 3)
    print(s2.x)
    print(' ')
    println(s2.y)
    println("")

    println("RECTANGLE")
    var r2 = Rect(1f, 3f, 10f, 4f)
    println("Rotation:")
    print(r2.x)
    print(' ')
    print(r2.y)
    print(" width=")
    print(r2.width)
    print(" height=")
    println(r2.height)
    r2.rotate(RotateDirection.Clockwise, 3, 3)
    print(r2.x)
    print(' ')
    print(r2.y)
    print(" width=")
    print(r2.width)
    print(" height=")
    println(r2.height)
    r2.rotate(RotateDirection.Clockwise, 3, 3)
    print(r2.x)
    print(' ')
    print(r2.y)
    print(" width=")
    print(r2.width)
    print(" height=")
    println(r2.height)
    r2.rotate(RotateDirection.Clockwise, 3, 3)
    print(r2.x)
    print(' ')
    print(r2.y)
    print(" width=")
    print(r2.width)
    print(" height=")
    println(r2.height)
    r2.rotate(RotateDirection.Clockwise, 3, 3)
    print(r2.x)
    print(' ')
    print(r2.y)
    print(" width=")
    print(r2.width)
    print(" height=")
    println(r2.height)
}